version: '3.3' 

services:
  mysql:
    image:  mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
  backend:
    image: shadifadila/my_repo:backend
    restart: always
    ports:
      - 5000:5000
    links:
      - mysql
  frontend:
    image: shadifadila/my_repo:frontend
    ports:
      - 81:5001
    links:
      - backend