#frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30080
---
#frontend Deployment
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: shadifadila/my_repo:frontend
    imagePullPolicy: Always
    ports:
      - containerPort: 5001